
import { Artisan, CraftType } from './types';

export const MOCK_ARTISANS: Artisan[] = [
  {
    id: '1',
    fullName: 'Anjali Das',
    parentName: 'Ramesh Das',
    dob: '1990-05-15',
    gender: 'Female',
    aadhaar: '1234 5678 9012',
    phone: '9876543210',
    email: 'anjali.das@example.com',
    education: '12th Pass',
    photo: null,
    address: 'House No. 12, Main Road',
    state: 'Assam',
    district: 'Kamrup',
    pincode: '781001',
    category: 'OBC',
    minority: 'No',
    bankName: 'State Bank of India',
    accountNumber: '1122334455',
    ifscCode: 'SBIN0001234',
    craftType: CraftType.Handloom,
    experience: '10',
    training: 'Yes',
    trainingDetails: 'Weaving course by NEHHDC',
    certification: 'Handloom Mark',
  },
  {
    id: '2',
    fullName: 'Bimal Singh',
    parentName: 'Kiran Singh',
    dob: '1985-02-20',
    gender: 'Male',
    aadhaar: '2345 6789 0123',
    phone: '9876543211',
    email: 'bimal.singh@example.com',
    education: 'Graduate',
    photo: null,
    address: 'Near Community Hall',
    state: 'Manipur',
    district: 'Imphal West',
    pincode: '795001',
    category: 'GEN',
    minority: 'No',
    bankName: 'HDFC Bank',
    accountNumber: '2233445566',
    ifscCode: 'HDFC0005678',
    craftType: CraftType.Handicraft,
    experience: '15',
    training: 'No',
    certification: 'GI Tag',
  },
  {
    id: '3',
    fullName: 'Chitra Reang',
    parentName: 'Sanjay Reang',
    dob: '1995-11-30',
    gender: 'Female',
    aadhaar: '3456 7890 1234',
    phone: '9876543212',
    email: 'chitra.reang@example.com',
    education: '10th Pass',
    photo: null,
    address: 'Village Agartala',
    state: 'Tripura',
    district: 'West Tripura',
    pincode: '799001',
    category: 'ST',
    minority: 'Yes',
    bankName: 'UCO Bank',
    accountNumber: '3344556677',
    ifscCode: 'UCBA0009101',
    craftType: CraftType.Handicraft,
    experience: '5',
    training: 'Yes',
    trainingDetails: 'Bamboo craft workshop',
    certification: 'None',
  },
];
